discus/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talk.urls', namespace='shop')),
    

]

talk/urls.py
from django.urls import path
from . import views
from django.contrib import admin

# from discus import talk

app_name ='talk'

urlpatterns = [
    path('', views.main_view, name ='main_view'),
    path('addInForum/',views.addInForum,name='addInForum'),
    path('addInDiscussion/', views.addInDiscussion,name='addInDiscussion'),

]

talk/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Forum(models.Model):
    name = models.CharField(max_length=200, default='anonymous')
    email = models.EmailField(max_length=200, null = True)
    topic = models.CharField(max_length=200)
    description = models.TextField(max_length=4000, blank =True)
    link = models.CharField(max_length=100, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Discussion(models.Model):
    forum = models.ForeignKey(Forum,  blank=True, on_delete=CASCADE)
    discuss = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.forum)

talk/forms.py
from django.forms import ModelForm
from .models import *

class CreateInForum(ModelForm):
    class Meta:
        model = Forum
        fields = "__all__"

class CreateInDiscussion(ModelForm):
    class Meta:
        model = Discussion
        fields = "__all__"

talk/views.py
from django.shortcuts import render, redirect
from .models import Forum, Discussion
from .forms import *
# Create your views here.

def main_view(request):
    forums =Forum.objects.all()
    count = forums.count()
    discussions =[]
    for i in forums:
        discussions.append(i.discussion_set.all())

    context = {'forums':forums, 'count':count, 'discussions':discussions}
    return render(request, 'talk/main_view.html', context)


def addInForum(request):
    form = CreateInForum()
    if request.method == 'POST':
        form = CreateInForum(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context ={'form':form}
    return render(request,'talk/addInForum.html',context)

def addInDiscussion(request):
    form = CreateInDiscussion()
    if request.method == 'POST':
        form = CreateInDiscussion(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context ={'form':form}
    return render(request,'talk/addInDiscussion.html',context)
 

talk/templates/talk/addInDiscussion.html
<head>
    <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    
</head>
<form action="{% url 'talk:addInDiscussion' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="submit">
</form>

talk/templates/talk/addInForum.html
<head>
    <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    
</head>
<form action="{% url 'talk:addInForum' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="submit">
</form>

talk/templates/talk/main_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Discussion forum</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    <style>
        .box{
            border: 4px solid black;
            margin: 0 auto;
        }
    </style>
</head>
<body>
        <h2 class="jumbotron">
            Currently active forums: {{count}}
            <form method="POST" action="{% url 'talk:addInForum' %}">
                {% csrf_token %}
            <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px;">Add more</button>
            </form>
        </h2>
            <div class="card-columns" style="padding: 10px; margin: 20px;"></div>
            
            
            {%for forum in forums %}
            
                <div class="card box container">
                    <br>
                    <h5 class="card-title">
                        <a href='{{forum.link}}'><h3>{{forum.topic}}</h3></a> 
                        <div class="card-body container">
                                <p>{{forum.description}}</p>
                            </h5>
                            <hr>
                            <p> By: {{forum.name}}</p>
                            email- {{forum.email}}
                            <hr>     
                            <h4>Views from other users</h4>
                            {%for discuss in discussions%}
                            {%for objs in discuss%}  
                            {% if objs.forum == forum %}
                               {{objs.discuss}}
                               <br>
                            {% endif %}
                            {%endfor%}
                            {%endfor%}
                            <form method="POST" action="{% url 'talk:addInDiscussion' %}">
                                {% csrf_token %}
                            <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px;">Add more</button>
                            </form>
                        </div>
                </div>
            </div>
            <br>
            
            {% endfor %}
          
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>